module Docker
  module HTTP
    # HTTP Methods
    OPTIONS = 'OPTIONS'
    GET     = 'GET'
    HEAD    = 'HEAD'
    POST    = 'POST'
    PUT     = 'PUT'
    DELETE  = 'DELETE'
    TRACE   = 'TRACE'
    CONNECT = 'CONNECT'
    PATCH   = 'PATCH'

    # HTTP Headers
    ACCEPT = 'Accept'
    ACCEPT_CHARSET = 'Accept-Charset'
    ACCEPT_ENCODING = 'Accept-Encoding'
    ACCEPT_LANGUAGE = 'Accept-Language'
    ACCEPT_RANGES = 'Accept-Ranges'
    AGE = 'Age'
    ALLOW = 'Allow'
    AUTHORIZATION = 'Authorization'
    CACHE_CONTROL = 'Cache-Control'
    CONNECTION = 'Connection'
    CONTENT_ENCODING = 'Content-Encoding'
    CONTENT_LANGUAGE = 'Content-Language'
    CONTENT_LENGTH = 'Content-Length'
    CONTENT_LOCATION = 'Content-Location'
    CONTENT_MD5 = 'Content-MD5'
    CONTENT_RANGE = 'Content-Range'
    CONTENT_TYPE = 'Content-Type'
    DATE = 'Date'
    ETAG = 'ETag'
    EXPECT = 'Expect'
    EXPIRES = 'Expires'
    FROM = 'From'
    HOST = 'Host'
    IF_MATCH = 'If-Match'
    IF_MODIFIED_SINCE = 'If-Modified-Since'
    IF_NONE_MATCH = 'If-None-Match'
    IF_RANGE = 'If-Range'
    IF_UNMODIFIED_SINCE = 'If-Unmodified-Since'
    IF_LAST_MODIFIED = 'If-Last-Modified'
    LOCATION = 'Location'
    MAX_FORWARDS = 'Max-Forwards'
    PRAGMA = 'Pragma'
    RANGE = 'Range'
    REFERER = 'Referer'
    RETRY_AFTER = 'Retry-After'
    SERVER = 'Server'
    KEEP_ALIVE = 'Keep-Alive'
    PROXY_AUTHENTICATE = 'Proxy-Authenticate'
    PROXY_AUTHORIZATION = 'Proxy-Authorization'
    TE = 'TE'
    TRAILER = 'Trailer'
    TRANSFER_ENCODING = 'Transfer-Encoding'
    UPGRADE = 'Upgrade'
    USER_AGENT = 'User-Agent'
    VARY = 'Vary'
    VIA = 'Via'
    WARNING = 'Warning'
    WWW_AUTHENTICATE = 'WWW-Authenticate'

    # Faster !
    constants.each do |name|
      v = const_get(name)
      v.freeze if v.kind_of?(String)
    end
  end
end
